// posts-app-svelte/src/screens/View.svelte
<script>
  import axios from 'axios';
  import Loading from '../components/Loading.svelte';
  export let params;

  let post;

  axios.get(process.env.API_URL + params.id).then(({ data }) => {
    post = data;
  });
</script>

{#if post}
  <h1>{post.title}</h1>
  <div class="ql-snow">
    <div class="ql-editor">
      {@html post.body}
    </div>
  </div>
{:else}
  <Loading />
{/if}

<style>
  .ql-snow {
    margin: 1.5rem -15px;
  }
</style>

// posts-app-react/src/screens/View.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useParams } from 'react-router-dom';
import { Typography } from '@material-ui/core';
import { ShowText } from '../components/TextEditor';
import Loading from '../components/Loading';

const View = () => {
  const { id } = useParams();
  const [post, setPost] = useState();

  useEffect(() => {
    axios.get(process.env.REACT_APP_URL_API + id).then(({ data }) => setPost(data));
  }, [id]);

  if (!post) return <Loading />;

  return (
    <>
      <Typography variant="h3" component="h1">{post.title}</Typography>
      <ShowText text={post.body} style={{ margin: '1.5rem -15px' }} />
    </>
  );
};

export default View;
