// posts-app-react/src/screens/App.jsx
import React from 'react';
import styled from 'styled-components';
import { Container, Button, Divider } from '@material-ui/core';
import { BrowserRouter, Switch, Route } from 'react-router-dom';
import Home from './Home';
import Post from './Post';

const Menu = styled.nav`
  margin-top: 3rem;

  & > * {
    margin: 0 .5rem .5rem 0;
  }
`;

const App = () => (
  <BrowserRouter>
    <Container maxWidth="md" fixed>
      <Menu>
        <Button variant="contained" color="primary" href="/">Home</Button>
        <Button variant="contained" color="primary" href="/post/new">New Post</Button>
      </Menu>
      <Divider />
      <Switch>
          <Route path="/post/:id">
            <Post />
          </Route>
          <Route path="/view/:id">
            {() => 'view'}
          </Route>
          <Route path="/">
            <Home />
          </Route>
        </Switch>
      </Container>
  </BrowserRouter>
);

export default App;

// posts-app-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'posts-app-angular';
}

<div class="container-app">
  <a mat-raised-button color="primary" href="/">HOME</a>
  <a mat-raised-button color="primary" href="/post/new">NEW POST</a>
  <mat-divider></mat-divider>

  <router-outlet></router-outlet>
</div>
