// posts-app-svelte/src/screens/Post.svelte
<script>
  import { onMount, createEventDispatcher } from 'svelte';
  import { pop } from 'svelte-spa-router'
  import { Button } from 'sveltestrap';
  import axios from 'axios';
  import Loading from '../components/Loading.svelte';
  export let params;

  $: isUpdate = params.id !== 'new';
  let post;
  const dispatch = createEventDispatcher();

  onMount(() => {
    if (isUpdate) {
      axios.get(process.env.API_URL + params.id).then(({ data }) => {
        post = data;
        post._id = undefined;
      });
    } else {
      post = {};
    }
  })

  const save = async () => {
    if (!(post.title && post.description && post.body)) {
      return dispatch('routeEvent', { text: 'All fields are required!', color: 'danger' });
    }
    if (isUpdate) {
      await axios.put(process.env.API_URL + params.id, post);
    } else {
      await axios.post(process.env.API_URL, post);
    }
    dispatch('routeEvent', { text: `Post ${isUpdate ? 'updated' : 'created'} successfully!`, });
    pop();
  };
</script>

<h1>{isUpdate ? 'Update' : 'Create'} Post</h1>

{#if post}
  <input bind:value={post.title} placeholder="Title" class="form-control" />
  <textarea bind:value={post.description} placeholder="Description" class="form-control" rows="3" />
  <textarea bind:value={post.body} placeholder="Post body" class="form-control" rows="3" />

  <div id="actions">
    <Button color="primary" on:click={save}>SAVE</Button>
    <Button on:click={pop}>CANCEL</Button>
  </div>
{:else}
  <Loading />
{/if}

<style>
  input, textarea, #actions {
    margin: .8rem 0;
    resize: none;
  }
  #actions > :global(*) {
    margin-right: .5rem;
  }
</style>

// posts-app-angular/src/app/screens/post/post.component.ts
import { Component } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import axios from 'axios';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-post',
  templateUrl: './post.component.html',
  styleUrls: ['./post.component.css']
})
export class PostComponent {
  post;
  isUpdate;

  constructor(
    private location: Location,
    private route: ActivatedRoute
  ) {
    const id = this.route.snapshot.paramMap.get('id');
    this.isUpdate = id !== 'new';
    if (this.isUpdate) {
      axios.get(environment.apiUrl + id).then(({ data }) => {
        this.post = data;
      });
    } else {
      this.post = {
        title: '',
        description: '',
        body: ''
      }
    }
  }

  save() {
    if (!(this.post.title && this.post.description)) {
      return alert('All fields are required!');
    }
    if (this.isUpdate) {
      const { _id } = this.post;
      this.post._id = undefined;
      axios.put(environment.apiUrl + _id, this.post);
    } else {
      axios.post(environment.apiUrl, this.post);
    }
    alert(`Post ${this.isUpdate ? 'updated' : 'created'} successfully!`);
    this.location.back();
  }

  cancel() {
    this.location.back();
  }
}

<h1>{{isUpdate ? 'Update' : 'Create'}} Post</h1>

<h1 *ngIf="!post">Loading</h1>

<div *ngIf="post">
  <mat-form-field appearance="outline">
    <mat-label>Title</mat-label>
    <input [(ngModel)]="post.title" matInput autofocus />
  </mat-form-field>
  <mat-form-field appearance="outline">
    <mat-label>Description</mat-label>
    <textarea
      [(ngModel)]="post.description"
      matInput
      cdkTextareaAutosize
      cdkAutosizeMinRows="2"
      cdkAutosizeMaxRows="5"
    ></textarea>
  </mat-form-field>

  <a mat-raised-button color="primary" (click)="save()">SAVE</a>
  <a mat-raised-button (click)="cancel()">CANCEL</a>
</div>
