// posts-app-angular/src/app/components/card/card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css']
})
export class CardComponent {
  confirm = false;
  @Input() title;
  @Input() description;
  @Output() view = new EventEmitter();
  @Output() edit = new EventEmitter();
  @Output() remove = new EventEmitter();
}

<div class="card-container">
  <h1 (click)="view.emit()">{{title}}</h1>
  <p>{{description}}</p>

  <div class="card-actions">
    <div *ngIf="!confirm">
      <mat-icon class="material-icons-outlined" (click)="view.emit()">visibility</mat-icon>
      <mat-icon class="material-icons-outlined" (click)="edit.emit()">edit</mat-icon>
      <mat-icon class="material-icons-outlined" (click)="confirm = true">delete</mat-icon>
    </div>

    <div *ngIf="confirm" class="card-confirm">
      <span>Do you really want to remove?</span>
      <mat-icon (click)="remove.emit()">done</mat-icon>
      <mat-icon (click)="confirm = false">close</mat-icon>
    </div>
  </div>
</div>

// posts-app-svelte/src/components/Card.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  export let title;
  export let description;

  const dispatch = createEventDispatcher();
  let confirm = false;
</script>

<div class="card">
  <h4 on:click={() => dispatch('view')}>{title}</h4>
  <p>{description}</p>

  <div class="actions">
    {#if confirm}
      <span>Do you really want to remove?</span>
      <i class="material-icons-outlined" on:click={() => dispatch('remove')}>done</i>
      <i class="material-icons-outlined" on:click={() => confirm = false}>close</i>
    {:else}
      <i class="material-icons-outlined" on:click={() => dispatch('view')}>visibility</i>
      <i class="material-icons-outlined" on:click={() => dispatch('edit')}>edit</i>
      <i class="material-icons-outlined" on:click={() => confirm = true}>delete</i>
    {/if}
  </div>
</div>

<style scoped>
  .card {
    position: relative;
    border: solid .02rem #DDD;
    border-radius: 4px;
    padding: .8rem;
    margin-bottom: 1rem;
  }
  h4 {
    width: fit-content;
    cursor: pointer;
  }
  h4:hover {
    opacity: .7;
  }
  p {
    margin: 0;
  }
  .actions {
    position: absolute;
    top: 0;
    right: 0;
    padding: .8rem;
    display: none;
    background: #FFF;
    font-size: 1.1rem;
  }
  .card:hover > .actions {
    display: block;
  }
  .actions > :not(span) {
    display: inline-flex;
    vertical-align: top;
    margin-left: .5rem;
    cursor: pointer;
  }
  .actions > :not(span):hover {
    opacity: .7;
  }
</style>
