// posts-app-react/src/screens/Post.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import styled from 'styled-components';
import { useParams, useHistory } from 'react-router-dom';
import { NotificationManager } from 'react-notifications';
import { Typography, TextField, Button } from '@material-ui/core';
import TextEditor from '../components/TextEditor';
import Loading from '../components/Loading';

const Container = styled.div`
  & > * {
    margin: .6rem 0 .2rem 0;
  }
`;

const Actions = styled.div`
  margin-top: 1rem;

  & > * {
    margin-right: .6rem;
  }
`;

const Post = () => {
  const history = useHistory();
  const { id } = useParams();
  const isUpdate = id !== 'new';
  const [post, setPost] = useState({});

  useEffect(() => {
    if (isUpdate) axios.get(process.env.REACT_APP_URL_API + id).then(({ data }) => setPost(data));
  }, [id, isUpdate]);

  if (isUpdate && !post._id) return <Loading />;

  const save = async () => {
    if (!(post.title && post.description && post.body)) {
      return NotificationManager.error('All fields are required!');
    }
    if (isUpdate) {
      post._id = undefined;
      await axios.put(process.env.REACT_APP_URL_API + id, post);
    } else {
      await axios.post(process.env.REACT_APP_URL_API, post);
    }
    NotificationManager.success(`Post ${isUpdate ? 'updated' : 'created'} successfully!`);
    history.push('..');
  };

  return (
    <Container>
      <Typography variant="h3" component="h1">
        {isUpdate ? 'Update Post' : 'Create Post'}
      </Typography>
      <TextField
        label="Title"
        variant="outlined"
        fullWidth
        defaultValue={post.title}
        onChange={(e) => { post.title = e.target.value; }}
      />
      <TextField
        label="Description"
        variant="outlined"
        multiline
        rows={2}
        rowsMax={5}
        fullWidth
        defaultValue={post.description}
        onChange={(e) => { post.description = e.target.value; }}
      />
      <TextEditor
        placeholder="Post body"
        defaultValue={post.body}
        onChange={(value) => { post.body = value; }}
      />
      <Actions>
        <Button variant="contained" color="primary" onClick={save}>Save</Button>
        <Button variant="contained" onClick={() => history.goBack()}>Cancel</Button>
      </Actions>
    </Container>
  );
};

export default Post;

// posts-app-svelte/src/screens/Post.svelte
<script>
  import { onMount, createEventDispatcher } from 'svelte';
  import { pop } from 'svelte-spa-router';
  import { Button } from 'sveltestrap';
  import axios from 'axios';
  import Loading from '../components/Loading.svelte';
  import TextEditor from '../components/TextEditor.svelte';
  export let params;

  const dispatch = createEventDispatcher();
  $: isUpdate = params.id !== 'new';
  let post;

  onMount(() => {
    if (isUpdate) {
      axios.get(process.env.API_URL + params.id).then(({ data }) => {
        post = data;
        post._id = undefined;
      });
    } else {
      post = {};
    }
  });

  const save = async () => {
    if (!(post.title && post.description && post.body)) {
      return dispatch('routeEvent', { text: 'All fields are required!', color: 'danger' });
    }
    if (isUpdate) {
      await axios.put(process.env.API_URL + params.id, post);
    } else {
      await axios.post(process.env.API_URL, post);
    }
    dispatch('routeEvent', { text: `Post ${isUpdate ? 'updated' : 'created'} successfully!` });
    pop();
  };
</script>

<h1>{isUpdate ? 'Update' : 'Create'} Post</h1>

{#if post}
  <input bind:value={post.title} placeholder="Title" class="form-control" />
  <textarea bind:value={post.description} placeholder="Description" class="form-control" rows="3" />
  <TextEditor bind:value={post.body} placeholder="Post body" />

  <div id="actions">
    <Button color="primary" on:click={save}>SAVE</Button>
    <Button on:click={pop}>CANCEL</Button>
  </div>
{:else}
  <Loading />
{/if}

<style>
  input, textarea, #actions {
    margin: .8rem 0;
    resize: none;
  }
  #actions > :global(*) {
    margin-right: .5rem;
  }
</style>
