// posts-app-react/src/screens/Home.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useHistory } from 'react-router-dom';
import { Typography } from '@material-ui/core';
import { NotificationManager } from 'react-notifications';
import SearchBar from '../components/SearchBar';
import Loading from '../components/Loading';
import Card from '../components/Card';

const Home = () => {
  const [posts, setPosts] = useState();
  const [search, setSearch] = useState('');
  const history = useHistory();

  useEffect(() => {
    if (!posts) axios.get(process.env.REACT_APP_URL_API).then(({ data }) => setPosts(data));
  }, [posts]);

  if (!posts) return <Loading />;

  const remove = async (post) => {
    await axios.delete(process.env.REACT_APP_URL_API + post._id);
    setPosts();
    setSearch('');
    NotificationManager.success(`Post removed successfully!`);
  };

  const resultPosts = posts.filter(
    p => p.title.indexOf(search) >= 0 || p.description.indexOf(search) >= 0
  );

  return (
    <>
      <SearchBar onChange={setSearch} />
      {resultPosts.length ? (
        resultPosts.map((post) => (
          <Card
            key={post._id}
            title={post.title}
            description={post.description}
            onView={() => history.push(`view/${post._id}`)}
            onEdit={() => history.push(`post/${post._id}`)}
            onRemove={() => remove(post)}
          />
        ))
      ) : (
        <Typography variant="h5" component="h3">
          Nothing added yet
        </Typography>
      )}
    </>
  );
};

export default Home;

// posts-app-vue/src/screens/Home.vue
<template>
  <div>
    <SearchBar @change="onSearch($event)"/>
    <Loading v-if="!filteredPosts"/>
    <Card
      v-for="p in filteredPosts"
      :key="p._id"
      :title="p.title"
      :description="p.description"
      @view="$router.push(`/view/${p._id}`)"
      @edit="$router.push(`/post/${p._id}`)"
      @remove="onRemove(p._id)"
    />
    <h4 v-if="filteredPosts && !filteredPosts.length">Nothing added yet</h4>
  </div>
</template>

<script>
  import axios from 'axios';
  import Card from '../components/Card.vue';
  import Loading from '../components/Loading.vue';
  import SearchBar from '../components/SearchBar.vue';

  export default {
    name: 'Home',
    components: {
      Card,
      Loading,
      SearchBar
    },
    data: () => ({
      posts: null,
      search: '',
      filteredPosts: null
    }),
    methods: {
      onSearch(search = this.search) {
        this.search = search;
        this.filteredPosts = this.posts.filter(
          p => p.title.indexOf(search) >= 0 || p.description.indexOf(search) >= 0
        );
      },
      async onRemove(id) {
        this.filteredPosts = null;
        await axios.delete(process.env.VUE_APP_URL_API + id);

        this.$bvToast.toast('Post removed successfully!', {
          noCloseButton: true,
          variant: 'success'
        });

        axios.get(process.env.VUE_APP_URL_API).then(({ data }) => {
          this.posts = data;
          this.onSearch();
        });
      }
    },
    mounted() {
      axios.get(process.env.VUE_APP_URL_API).then(({ data }) => {
        this.posts = data;
        this.filteredPosts = data;
      });

      if (this.$route.query.m) {
        this.$bvToast.toast(`Post ${this.$route.query.m} successfully!`, {
          noCloseButton: true,
          variant: 'success'
        });
        this.$router.replace('/');
      }
    }
  };
</script>
