// posts-app-angular/src/app/screens/home/home.component.ts
import { Component } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { Router } from '@angular/router';
import axios from 'axios';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  search = '';
  posts;
  filteredPosts;

  constructor(
    private router: Router,
    private toastr: ToastrService
  ) {
    this.loadPosts();
  }

  async loadPosts() {
    await axios.get(environment.apiUrl).then(({ data }) => {
      this.posts = data;
      this.filteredPosts = data;
    });
  }

  onSearch() {
    this.filteredPosts = this.posts?.filter(
      p => p.title.indexOf(this.search) >= 0 || p.description.indexOf(this.search) >= 0
    );
  }

  async onRemove(id) {
    this.posts = this.filteredPosts = null;
    await axios.delete(environment.apiUrl + id);
    this.toastr.success('Post removed successfully!');
    await this.loadPosts();
    this.onSearch();
  }

  redirect(url) {
    this.router.navigateByUrl(url);
  }
}

<mat-form-field appearance="outline">
  <mat-label>Search</mat-label>
  <input
    matInput
    type="search"
    [(ngModel)]="search"
    (input)="onSearch()"
  />
  <mat-icon matSuffix>search</mat-icon>
</mat-form-field>

<app-loading *ngIf="!posts"></app-loading>

<app-card
  *ngFor="let post of filteredPosts"
  [title]="post.title"
  [description]="post.description"
  (view)="redirect('view/' + post._id)"
  (edit)="redirect('post/' + post._id)"
  (remove)="onRemove(post._id)"
></app-card>

<h1 *ngIf="posts && !filteredPosts.length">Nothing added yet</h1>

// posts-app-vue/src/screens/Home.vue
<template>
  <div>
    <SearchBar @change="onSearch($event)"/>
    <Loading v-if="!filteredPosts"/>
    <Card
      v-for="p in filteredPosts"
      :key="p._id"
      :title="p.title"
      :description="p.description"
      @view="$router.push(`/view/${p._id}`)"
      @edit="$router.push(`/post/${p._id}`)"
      @remove="onRemove(p._id)"
    />
    <h4 v-if="filteredPosts && !filteredPosts.length">Nothing added yet</h4>
  </div>
</template>

<script>
  import axios from 'axios';
  import Card from '../components/Card.vue';
  import Loading from '../components/Loading.vue';
  import SearchBar from '../components/SearchBar.vue';

  export default {
    name: 'Home',
    components: {
      Card,
      Loading,
      SearchBar
    },
    data: () => ({
      posts: null,
      search: '',
      filteredPosts: null
    }),
    methods: {
      onSearch(search = this.search) {
        this.search = search;
        this.filteredPosts = this.posts.filter(
          p => p.title.indexOf(search) >= 0 || p.description.indexOf(search) >= 0
        );
      },
      async onRemove(id) {
        this.filteredPosts = null;
        await axios.delete(process.env.VUE_APP_URL_API + id);

        this.$bvToast.toast('Post removed successfully!', {
          noCloseButton: true,
          variant: 'success'
        });

        axios.get(process.env.VUE_APP_URL_API).then(({ data }) => {
          this.posts = data;
          this.onSearch();
        });
      }
    },
    mounted() {
      axios.get(process.env.VUE_APP_URL_API).then(({ data }) => {
        this.posts = data;
        this.filteredPosts = data;
      });

      if (this.$route.query.m) {
        this.$bvToast.toast(`Post ${this.$route.query.m} successfully!`, {
          noCloseButton: true,
          variant: 'success'
        });
        this.$router.replace('/');
      }
    }
  };
</script>
