// posts-app-svelte/src/screens/View.svelte
<script>
  import axios from 'axios';
  import Loading from '../components/Loading.svelte';
  export let params;

  let post;

  axios.get(process.env.API_URL + params.id).then(({ data }) => {
    post = data;
  });
</script>

{#if post}
  <h1>{post.title}</h1>
  <div class="ql-snow">
    <div class="ql-editor">
      {@html post.body}
    </div>
  </div>
{:else}
  <Loading />
{/if}

<style>
  .ql-snow {
    margin: 1.5rem -15px;
  }
</style>

// posts-app-vue/src/screens/View.vue
<template>
  <div>
    <Loading v-if="!post.title"/>
    <h1>{{post.title}}</h1>
    <div class="ql-snow">
      <div class="ql-editor" v-html="post.body"/>
    </div>
  </div>
</template>

<script>
  import axios from 'axios';
  import Loading from '../components/Loading.vue';

  export default {
    name: 'ViewPost',
    components: {
      Loading
    },
    data: () => ({
      post: {}
    }),
    mounted() {
      axios.get(process.env.VUE_APP_URL_API + this.$route.params.id)
        .then(({ data }) => {
          this.post = data;
        });
    }
  };
</script>

<style scoped>
  .ql-snow {
    margin: 1.5rem -15px;
  }
</style>
